// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderViewer.Data;

#nullable disable

namespace OrderViewer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250702150456_SeedDemoOrders")]
    partial class SeedDemoOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderViewer.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 3, 30, 17, 4, 55, 376, DateTimeKind.Local).AddTicks(8544),
                            Customer = "Customer 1",
                            Paid = true,
                            Status = "Shipped",
                            Total = 245.15m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 6, 29, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7535),
                            Customer = "Customer 2",
                            Paid = false,
                            Status = "Pending",
                            Total = 65.08m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 4, 14, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7643),
                            Customer = "Customer 3",
                            Paid = false,
                            Status = "Processing",
                            Total = 290.23m
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 4, 7, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7668),
                            Customer = "Customer 4",
                            Paid = false,
                            Status = "Processing",
                            Total = 119.04m
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 4, 2, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7687),
                            Customer = "Customer 5",
                            Paid = false,
                            Status = "Processing",
                            Total = 280.47m
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 6, 3, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7715),
                            Customer = "Customer 6",
                            Paid = true,
                            Status = "Processing",
                            Total = 387.78m
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 5, 9, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7728),
                            Customer = "Customer 7",
                            Paid = false,
                            Status = "Processing",
                            Total = 127.28m
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 5, 30, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7743),
                            Customer = "Customer 8",
                            Paid = true,
                            Status = "Processing",
                            Total = 121.17m
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 4, 20, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7762),
                            Customer = "Customer 9",
                            Paid = true,
                            Status = "Cancelled",
                            Total = 279.01m
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 4, 29, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7782),
                            Customer = "Customer 10",
                            Paid = false,
                            Status = "Cancelled",
                            Total = 98.77m
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 6, 6, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7809),
                            Customer = "Customer 11",
                            Paid = true,
                            Status = "Shipped",
                            Total = 178.83m
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 4, 12, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7821),
                            Customer = "Customer 12",
                            Paid = true,
                            Status = "Cancelled",
                            Total = 251.47m
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 5, 6, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7842),
                            Customer = "Customer 13",
                            Paid = true,
                            Status = "Shipped",
                            Total = 159.55m
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 5, 3, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7856),
                            Customer = "Customer 14",
                            Paid = true,
                            Status = "Processing",
                            Total = 464.85m
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 4, 8, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7870),
                            Customer = "Customer 15",
                            Paid = false,
                            Status = "Shipped",
                            Total = 334.35m
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2025, 4, 2, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7892),
                            Customer = "Customer 16",
                            Paid = false,
                            Status = "Shipped",
                            Total = 206.27m
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2025, 5, 7, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7908),
                            Customer = "Customer 17",
                            Paid = true,
                            Status = "Pending",
                            Total = 100.43m
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2025, 5, 28, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7928),
                            Customer = "Customer 18",
                            Paid = true,
                            Status = "Shipped",
                            Total = 537.82m
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2025, 5, 10, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7945),
                            Customer = "Customer 19",
                            Paid = false,
                            Status = "Pending",
                            Total = 88.96m
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2025, 5, 15, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7966),
                            Customer = "Customer 20",
                            Paid = true,
                            Status = "Pending",
                            Total = 163.62m
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2025, 4, 7, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7980),
                            Customer = "Customer 21",
                            Paid = false,
                            Status = "Cancelled",
                            Total = 212.00m
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2025, 3, 27, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(7994),
                            Customer = "Customer 22",
                            Paid = false,
                            Status = "Cancelled",
                            Total = 121.29m
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2025, 4, 4, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8013),
                            Customer = "Customer 23",
                            Paid = true,
                            Status = "Pending",
                            Total = 324.73m
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2025, 6, 11, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8027),
                            Customer = "Customer 24",
                            Paid = true,
                            Status = "Processing",
                            Total = 196.59m
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2025, 7, 1, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8044),
                            Customer = "Customer 25",
                            Paid = false,
                            Status = "Cancelled",
                            Total = 130.17m
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2025, 6, 13, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8063),
                            Customer = "Customer 26",
                            Paid = false,
                            Status = "Pending",
                            Total = 166.23m
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2025, 5, 30, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8076),
                            Customer = "Customer 27",
                            Paid = true,
                            Status = "Cancelled",
                            Total = 526.59m
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2025, 4, 7, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8094),
                            Customer = "Customer 28",
                            Paid = false,
                            Status = "Shipped",
                            Total = 360.82m
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2025, 4, 25, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8113),
                            Customer = "Customer 29",
                            Paid = true,
                            Status = "Shipped",
                            Total = 310.18m
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2025, 3, 26, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8126),
                            Customer = "Customer 30",
                            Paid = true,
                            Status = "Cancelled",
                            Total = 443.26m
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTime(2025, 5, 10, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8144),
                            Customer = "Customer 31",
                            Paid = true,
                            Status = "Shipped",
                            Total = 220.86m
                        },
                        new
                        {
                            Id = 32,
                            CreatedDate = new DateTime(2025, 5, 17, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8161),
                            Customer = "Customer 32",
                            Paid = true,
                            Status = "Cancelled",
                            Total = 424.81m
                        },
                        new
                        {
                            Id = 33,
                            CreatedDate = new DateTime(2025, 5, 13, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8305),
                            Customer = "Customer 33",
                            Paid = true,
                            Status = "Shipped",
                            Total = 121.67m
                        },
                        new
                        {
                            Id = 34,
                            CreatedDate = new DateTime(2025, 6, 26, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8329),
                            Customer = "Customer 34",
                            Paid = false,
                            Status = "Pending",
                            Total = 211.82m
                        },
                        new
                        {
                            Id = 35,
                            CreatedDate = new DateTime(2025, 6, 13, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8344),
                            Customer = "Customer 35",
                            Paid = true,
                            Status = "Shipped",
                            Total = 327.61m
                        },
                        new
                        {
                            Id = 36,
                            CreatedDate = new DateTime(2025, 3, 31, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8358),
                            Customer = "Customer 36",
                            Paid = true,
                            Status = "Pending",
                            Total = 450.87m
                        },
                        new
                        {
                            Id = 37,
                            CreatedDate = new DateTime(2025, 5, 3, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8379),
                            Customer = "Customer 37",
                            Paid = false,
                            Status = "Processing",
                            Total = 108.92m
                        },
                        new
                        {
                            Id = 38,
                            CreatedDate = new DateTime(2025, 4, 28, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8390),
                            Customer = "Customer 38",
                            Paid = false,
                            Status = "Processing",
                            Total = 262.57m
                        },
                        new
                        {
                            Id = 39,
                            CreatedDate = new DateTime(2025, 6, 1, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8406),
                            Customer = "Customer 39",
                            Paid = false,
                            Status = "Pending",
                            Total = 453.62m
                        },
                        new
                        {
                            Id = 40,
                            CreatedDate = new DateTime(2025, 4, 29, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8425),
                            Customer = "Customer 40",
                            Paid = false,
                            Status = "Pending",
                            Total = 523.71m
                        },
                        new
                        {
                            Id = 41,
                            CreatedDate = new DateTime(2025, 4, 26, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8439),
                            Customer = "Customer 41",
                            Paid = true,
                            Status = "Pending",
                            Total = 515.38m
                        },
                        new
                        {
                            Id = 42,
                            CreatedDate = new DateTime(2025, 4, 28, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8456),
                            Customer = "Customer 42",
                            Paid = true,
                            Status = "Pending",
                            Total = 256.54m
                        },
                        new
                        {
                            Id = 43,
                            CreatedDate = new DateTime(2025, 4, 27, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8475),
                            Customer = "Customer 43",
                            Paid = false,
                            Status = "Processing",
                            Total = 334.37m
                        },
                        new
                        {
                            Id = 44,
                            CreatedDate = new DateTime(2025, 5, 28, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8489),
                            Customer = "Customer 44",
                            Paid = false,
                            Status = "Pending",
                            Total = 410.80m
                        },
                        new
                        {
                            Id = 45,
                            CreatedDate = new DateTime(2025, 6, 8, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8506),
                            Customer = "Customer 45",
                            Paid = true,
                            Status = "Cancelled",
                            Total = 499.72m
                        },
                        new
                        {
                            Id = 46,
                            CreatedDate = new DateTime(2025, 6, 8, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8522),
                            Customer = "Customer 46",
                            Paid = true,
                            Status = "Cancelled",
                            Total = 270.32m
                        },
                        new
                        {
                            Id = 47,
                            CreatedDate = new DateTime(2025, 5, 14, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8534),
                            Customer = "Customer 47",
                            Paid = false,
                            Status = "Cancelled",
                            Total = 364.64m
                        },
                        new
                        {
                            Id = 48,
                            CreatedDate = new DateTime(2025, 5, 12, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8555),
                            Customer = "Customer 48",
                            Paid = false,
                            Status = "Cancelled",
                            Total = 375.23m
                        },
                        new
                        {
                            Id = 49,
                            CreatedDate = new DateTime(2025, 4, 11, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8570),
                            Customer = "Customer 49",
                            Paid = true,
                            Status = "Processing",
                            Total = 487.23m
                        },
                        new
                        {
                            Id = 50,
                            CreatedDate = new DateTime(2025, 6, 15, 17, 4, 55, 381, DateTimeKind.Local).AddTicks(8584),
                            Customer = "Customer 50",
                            Paid = false,
                            Status = "Shipped",
                            Total = 204.68m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
